export const Numbers = {
  GAME_TIMEOUT_VARIATION: 1500,
  INDEX_NOT_FOUND: -1,
  NOTFOUND: 404,
  RANDOM_NEGTIVE: 0.5,
  SCORE_MILLISECONDS: 100,
  STEP_LEFT: 0,
  STEP_RIGHT: 1,
  USERNAME_LENGTH: 3,
  ZERO: 0,
};
